### ISSUE TITLE
remove mac "hidden" files

### ISSUE THREAD

**Issue by jradavenport** [RileyWClarke/QPP-GP#3]
the .DS_Store and .ipynb_checkpoints don't need to be added

You can create a [global .gitignore file](http://vallandingham.me/Quick_Git.html#add-global-gitignore-file-for-temporary-files) that makes it so these files are never included

**Comment by jradavenport** [comment]
Here is what my `~/.gitignore` contains:

````
*.swp
*.pyc
*.aux
.DS_Store
*.ipynb_checkpoints
````

**Comment by RileyWClarke** [comment]
I added those files to my ~/.gitignore, ran git config --global core.excludesfile ~/.gitignore, and did a git push, but files still showing up? Do I need to do something else?
