### ISSUE TITLE
Need a LICENSE.md file

### ISSUE THREAD

**Issue by jradavenport** [RileyWClarke/QPP-GP#4]
@dfm [suggests wisely](https://twitter.com/exoplaneteer/status/887459102623842304) that you add a license file so others can use your code.

**Comment by RileyWClarke** [comment]
Does the type of license matter?

**Comment by jradavenport** [comment]
Not especially. I tend to use the MIT license template that github provides. Check [this page](https://help.github.com/articles/licensing-a-repository/) out for some useful info, and [this blog post](http://www.astrobetter.com/blog/2014/03/10/the-whys-and-hows-of-licensing-scientific-code/) for some of the how/why of licensing your code!
